all: install

install:
	install -d /var/www/html/ffmpeg
	install -d /var/www/html/ffmpeg/js
	install ffmpeg-core.js /var/www/html/ffmpeg/ffmpeg-core.js
	install ffmpeg-core.worker.js /var/www/html/ffmpeg/ffmpeg-core.worker.js
	install ffmpeg.min.js /var/www/html/ffmpeg/ffmpeg.min.js
	install ffmpeg.min.js.map /var/www/html/ffmpeg/ffmpeg.min.js.map
	install concatDemuxer.html /var/www/html/ffmpeg/concatDemuxer.html
	install image2video.html /var/www/html/ffmpeg/image2video.html
	install transcode.html /var/www/html/ffmpeg/transcode.html
	install trim.html /var/www/html/ffmpeg/trim.html
	install webcam.html /var/www/html/ffmpeg/webcam.html
	install colmena_audio.html /var/www/html/ffmpeg/colmena_audio.html
	install main.css /var/www/html/ffmpeg/main.css
	install main.css.map /var/www/html/ffmpeg/main.css.map


